### ISSUE TITLE
[dvsim] fusesoc_core modification issue

### ISSUE THREAD

**Issue by desorya** [lowRISC/opentitan#22782]
Hi,
I tried the uart in dvsim as shown in the guidance and it works well.
However, when I try to modify the **uart_sim_cfg.hjson** with a file_path as below:
```
line 18,   fusesoc_core: lowrisc:dv:uart_sim:0.1
-> fusesoc_core: "{proj_root}/hw/ip/uart/dv/uart_sim.core"
```
I got an error saying:
```
File "/automation/opentitan/.venv/lib/python3.9/site-packages/fusesoc/coremanager.py", line 212, in _solve 
               request.install(Requirement._from_string(_top_dep))
File "/automation/opentitan/.venv/lib/python3.9/site-packages/simplesat/constraints/requirement.py", line 149, in _from_string
               named_constraints = parser.parse(string, version_factory)
File "/automation/opentitan/.venv/lib/python3.9/site-packages/simplesat/constraints/parser.py", line 224, in parse
               tokens_blocks = _tokenize(self._scanner, requirement_string)
File "/automation/opentitan/.venv/lib/python3.9/site-packages/simplesat/constraints/parser.py", line 154, in _tokenize raise
               InvalidConstraint(msg.format(requirement_string)) 
simplesat.errors.InvalidConstraint: '/automation/opentitan/hw/ip/uart/dv/uart_sim.core >= 0-0'(unparsed '/automation/opentitan/hw/ip/uart/dv/uart_sim.core >= 0-0')
                make: *** [gen_sv_flist] Error 1
```
*I'd like to ask that how should I set the attribute that could be loaded correctly by the system when I'm using my own .core file?*

I've also tried another approach that using a `.f` file list instead of `.core` file:
```
line18,    fusesoc_core: lowrisc:dv:uart_sim:0.1
->  sv_flist: ["{proj_root}/hw/ip/npu/dv/npu_sim.f"]
    sv_flist_gen_dir : "{proj_root}/hw/ip/npu/dv/"
```
But it results in a confliction:
```
INFO: [dvsim] [proj_root]: /automation/opentitan
ERROR: [CfgFactory] '/automation/opentitan/hw/dv/tools/dvsim/fusesoc.hjson': Value for key 'sv_flist_gen_dir' is '{build_dir}/sim-vcs', but we already had a conflicting value of '{proj_root}/hw/ip/npu/dv/'.
```
*I'd like to ask if it is possible to run dvsim in such way because for my ip block itself, it is much easier to get a `.f` file list than `.core` file.*

Thank you!

**Comment by rswarbrick** [comment]
The current OpenTitan build flow uses fusesoc to do the job of "Grab all the required modules and stick their .sv files somewhere sensible". The dvsim tool invokes fusesoc and then calls the needed EDA tool afterwards.

The `fusesoc_core` field in dvsim's hjson file is supposed to take the name of a core, rather than the path to the core file. When we invoke fusesoc, we're then saying "Please find core XYZ and all its dependencies, searching in the following tree ...".

For your use case, I suspect the easiest approach is to generate a simple core file. Honestly, there's not much more than the list of files, so you could probably (manually?) run some script to build it from your `.f` file list. The simplest way to do this would probably be to make a copy of the existing `uart.core` and:
- Change the name (line 5)
- Tweak the list of files
- Remove the `files_*_waiver` blocks (lines 22-44)
- Remove the lines that use those blocks (lines 55-57)

**Comment by desorya** [comment]
Sorry I'm a newbie at that.
I tried to create a core file `npu_sim.core`:
```
CAPI=2:
name: t:dv:npu_sim:0.1
description: "npu sim target"
filesets:
  files_rtl:
    files:
      - rtl/timescale.v
      - rtl/includes
      - file_list/rtl.f
      - file_list/asic.f
      - file_list/tb.f
      - ips/npu/NPU_module/RTL/NPU_pro_module_read_mem_set_reset.v

  files_ips:
    files:
      - file_list/ips.f
      - ips/npu/rtl/
      - ips/axi/axi_node/
      - ips/riscv/include
      - ips/adv_dbg_if/rtl/
      - ips/apb/apb_i2c/
      - ips/apb/apb_event_unit/include

  files_uvm:
    files:
      - file_list/UVM.f
      - file_list/tetraUVM.f
      - testlist.f

parameters:
  SYNTHESIS:
    datatype: bool
    paramtype: vlogdefine

targets:
  sim: &sim_target
    toplevel: tb
    filesets:
      - files_rtl
      - files_ips
      - files_uvm
    default_tool: vcs

  lint:
    <<: *sim_target
```
with my testbench `tb` in `npu_sim_cfg.hsjon`
```
tb: union_ctrl_top
tool: vcs
fusesoc_core: t:dv:npu_sim:0.1
```

But I encountered a building error:
```
Error-[TMENF-ILL] Top Module/Entity not found
  Top module/entity/config "union_ctrl_top" is not found in the following 
  library list.
  Liblist: work
```
I tried to put the `union_ctrl_top.sv` under `{proj_root}/hw/ip/npu/dv/` and `{proj_root}/hw/ip/npu/dv/union_ctrl_top/` but neither works.
*Could you please let me know where can I locate the liblist and how should I correct the core file? Supposing that I only need to use the dv sim through vcs.*

Thank you!

**Comment by rswarbrick** [comment]
Hmm that sounds annoying! And it's quite difficult to debug at a distance :-)

As a high-level comment, it might be worth knowing that entries in a core file are supposed to be (regular) files, rather than directories. And I can't see `union_ctrl_top.sv` in your list :-D

The easiest thing might be to copy an existing core file, which should have roughly the right structure. For example, the UART module has `uart_sim.core`, which looks like this:
```
name: "lowrisc:dv:uart_sim:0.1"
description: "UART DV sim target"
filesets:
  files_rtl:
    depend:
      - lowrisc:ip:uart

  files_dv:
    depend:
      - lowrisc:dv:uart_test
      - lowrisc:dv:uart_sva
    files:
      - tb/tb.sv
    file_type: systemVerilogSource

... blah blah ...
```
This is the testbench itself (notice `tb.sv`). It depends on two other cores (`lowrisc:dv:uart_test` and `lowrisc:dv:uart_sva`). You can probably ignore the SVA core file, but `uart_test` looks like this.
```
name: "lowrisc:dv:uart_test:0.1"
description: "UART DV UVM test"
filesets:
  files_dv:
    depend:
      - lowrisc:dv:uart_env
    files:
      - uart_test_pkg.sv
      - uart_base_test.sv: {is_include_file: true}
    file_type: systemVerilogSource

targets:
  default:
    filesets:
      - files_dv
```

This is a test (in the UVM sense), which ultimately derives from `uvm_test`. But that's not the interesting bit really: most of the UVM stuff actually comes from the `uart_env` core (which has a rather longer file list).

To get things working locally, I'd suggest you look in the scratch directory, which contains log files and also contains the output from `fusesoc` after it has collected up all the RTL files. The EDA tool will only ever see stuff that got copied to there. The log file from the EDA tool is `build.log`. This should contain the error you've just pasted. It will also show the command that actually got run to invoke VCS: it might then be obvious what is missing.

**Comment by desorya** [comment]
Hi @rswarbrick,
Sorry to bother you again, I've tried many times but the Entity Not Fount issue still cannot be overcame. I guess that issue results from the parsing process of the core file because the `.scr` file which is supposed to be a full file list under `cover_reg_top` is empty.
I'm not sure if the core file is able to parse `.f` file list as its component. I tried to create a set of core files corresponding to my `.f` file list and referred to my sim_env as uart_sim did. However the problem still exists. 
In my understanding, the `.scr` file plays the similar role as my `.f` file list, I wonder if it is possible to skip the parsing process by fusesoc and use the `.f` file list instead of the `.scr` file.
As similar to what I tried(but failed) before:
> ```
> line18,    fusesoc_core: lowrisc:dv:uart_sim:0.1
> ->  sv_flist: ["{proj_root}/hw/ip/npu/dv/npu_sim.f"]
>     sv_flist_gen_dir : "{proj_root}/hw/ip/npu/dv/"
> ```

If there's any correct way that allows me to designate a specific `sv_flist` using an existed file list and no need to regenerate one, I guess the issue will be fixed.

Thank you.

**Comment by rswarbrick** [comment]
Hi there. The `sv_flist` variable is supposed to contain a list of SV files, not the path of a file that itself contains such a list. I don't think there's an easy way to skip fusesoc in OpenTitan at the moment. One option might be for you to tweak dvsim to do so, but I suspect that passing sensible core files is easier.

It sounds like you're trying to build a tree of core files in the way I described above. That sounds sensible! You might find that you can manually run the fusesoc command yourself when debugging: that should make the turn-around much quicker for getting things running.

I'm not sure we can be much more specific: this isn't really something we can reproduce at this end.

**Comment by desorya** [comment]
Hi @rswarbrick,
One more question about the attributes in core file.
Taking uart as an example, if you run the command:
```
python util/dvsim/dvsim.py hw/ip/uart/dv/uart_sim_cfg.hjson -i uart_smoke
```
After building process, there is a `lowrisc_dv_uart_sim_0.1.scr` file under `scratch/master/uart-sim-vcs/default/sim-vcs/`, which contains the following part:
```
+incdir+../src/lowrisc_dv_dv_fcov_macros_0
+incdir+../src/lowrisc_dv_dv_macros_0
+incdir+../src/lowrisc_prim_assert_0.1/rtl
+incdir+../src/lowrisc_dv_mem_model_0
+incdir+../src/lowrisc_dv_dv_utils_0
+incdir+../src/lowrisc_dv_dv_base_reg_0
+incdir+../src/lowrisc_dv_csr_utils_0
``` 

The form of these lines looks like a directory, but I haven't found a way to include the dir path in the core file. The attributes of the core file appear to be exact files rather than the folders, as shown in `uart_sim.core`:
```
filesets:
  files_rtl:
    depend:
      - lowrisc:ip:uart

  files_dv:
    depend:
      - lowrisc:dv:uart_test
      - lowrisc:dv:uart_sva
    files:
      - tb/tb.sv
    file_type: systemVerilogSource
```

Back to my own case, if I have a `.f` file list `tag.f` needs to be converted into a core file and it contains:
```
rtl/timescale.v
+incdir+./rtl/includes 
+incdir+../ips/axi/axi_node/ 
```

And I have my core file here:
```
CAPI=2:
name: t:dv:npu_sim:0.1
description: "NPU simulation target"

filesets:
  files_rtl:
    depend:
      - t:dv:npu_sim_rtl:0.1

  files_ips:
    depend:
      - t:dv:npu_sim_ips:0.1

parameters:
  SYNTHESIS:
    datatype: bool
    paramtype: vlogdefine

targets:
  sim: &sim_target
    toplevel: tb
    filesets:
      - files_rtl
      - files_ips
    default_tool: vcs

  lint:
    <<: *sim_target
```
Now I need to add a new item `files_tag` under `filesets` which includes `timescale.v` and the paths. 
Could you please let me know how to incorporate the above path into the core file? My current approach is to add all the files under each path one by one, but this is absolutely inefficient.

Thank you!
