### ISSUE TITLE
[tools] fusesoc negate flag

### ISSUE THREAD

**Issue by tjaychen** [lowRISC/opentitan#4145]
In an attempt to work around #4144, i attempt to add the following to `otbn.core`

```
  files_rtl_top:
    depend:
      - lowrisc:ip:tlul
      - lowrisc:prim:all
      - lowrisc:prim:assert
      - lowrisc:prim:util
      - lowrisc:prim:ram_1p_adv
      - lowrisc:ip:otbn_pkg
      - !tool_ascentlint ? (lowrisc:dv:otbn_model)
    files:
      - rtl/otbn_reg_pkg.sv
      - rtl/otbn_reg_top.sv
      - rtl/otbn.sv
    file_type: systemVerilogSource
```
However, the fusesoc flow almost immediately dies. 
After some debugging, the flow is dying [here](https://github.com/lowRISC/fusesoc/blob/master/fusesoc/utils.py#L136).
It seems the yaml reader does not like the presence of an `!` in front.  I get the following error 

```
WARNING: Parse error. Ignoring file hw/ip/otbn/otbn.core: mapping keys are not allowed in this context
```

I can work around this by changing the negating to something like `(!)`, and then changing the corresponding [expression evaluation](https://github.com/lowRISC/fusesoc/blob/ot/fusesoc/capi2/exprs.py#L82).

It's not really clear to me what the right fix is, so I'm filing this issue here first. If what I observed is real, then this issue should probably be propagated to the fusesoc repository.
